#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
/usr/local/lsf/etc/job_starter 'crab_getoutput_job.sh /afs/cern.ch/work/c/cirkovic/hydjet/CMSSW_7_5_8_patch4/src/GeneratorInterface/Hydjet2Interface/test crab_20160725_145810 9201-9300'
ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
